### ISSUE TITLE
Warm cache on future post date 

### ISSUE THREAD

**Issue by wihodges** [putyourlightson/craft-blitz#56]
So this might be kind of an extension to #51 issue, but it appears that posts set in the future don't trigger warm cache once they reach their published time. 

Just updated to most recent version of Blitz 1.11.1 prior to this issue. 

I'll try to do a couple more entry scheduled posts to see if it is actually works or not.

**Comment by wihodges** [comment]
A did another test appears that scheduled posts don't trigger cache update.

**Comment by putyourlightson** [comment]
Have you rewarmed the cache since updating to 1.11.1 and set up a cron job to trigger the refresh as explained in https://github.com/putyourlightson/craft-blitz/issues/33#issuecomment-450870488 ?

**Comment by wihodges** [comment]
Oh somehow missed that thread. And yes cache was manually warmed after plugin update.

So could/should I run cron job command for ./craft blitz/cache/refresh-expired every 30mins?

**Comment by putyourlightson** [comment]
Yeah, the cron job frequency is completely up to you, every 30 minutes sounds reasonable.

**Comment by wihodges** [comment]
Ok sorry for probably dumb question, but refresh-expired I assume is only for entries that will expire not ones set to publish in future, in which case I should automate the warm cache with "./craft blitz/cache/warm" - Is there any performance issues with warming the cache repeatedly and often?

**Comment by putyourlightson** [comment]
It will also refresh entries with future post dates. I've explained it in more details in the docs here:
https://github.com/putyourlightson/craft-blitz#refresh-expired-blitz-cache

I would advise against warming the cache repeatedly and too often as the plugin is intended to intelligently keep the cache refreshed and warm.

**Comment by wihodges** [comment]
Ah weird so in my test I created a future post and when post time occurred, I manually triggered refresh-expired multiple times, and I didn't see any changes to frontend. I'll test again to verify.

**Comment by putyourlightson** [comment]
Ok, I looked into the logic of how this is set up and you might be right about entries with future post dates not being refreshed. I'll take a closer look next week and see if we can get a fix out.

**Comment by putyourlightson** [comment]
Fixed in version 1.11.2, please let me know if it is now working as expected. You'll need to resave entries for the future post or expire dates to register as there is a new database table to keep track of this.

**Comment by wihodges** [comment]
Hmm still doesn't seem to update the index page(s) calling the referenced post. The entry itself seems to be cached and viewable. I've got a cronjob as well as just triggering refresh-expired via command.

**Comment by putyourlightson** [comment]
Can you show me the element query code used on the index page?

**Comment by wihodges** [comment]
```
{% set entriesList = craft.entries.section('news').all() %}
{% for entries in entriesList %}
etc...
```
So just to verify as well, I set a future post, I can see the "blitz_elementexpirydates" entry being created, and I see it clear out of the table with refresh-expired.

**Comment by putyourlightson** [comment]
But the cached file is not refreshed? Can you verify this by checking the file's last modified date?

**Comment by wihodges** [comment]
So cache on future post page:  Cached by Blitz on 2019-01-08T14:47:16-06:00 -->
And cache on index page:  Cached by Blitz on 2019-01-08T10:03:02-06:00 -->

The future post page itself seems to cache immediately on schedule and even before I run refresh command. The index page, however, does not update no matter how many times I run refresh on command line or via utilities panel. Perhaps the entry is getting cleared out of blitz_elementexpirydates before the refresh command has a time to see it? 

My test process: Create future post, wait for time of post, check post page [success loads and cached], check index page [no change], initiate refresh-expired [get confirmation "Expired Blitz cache successfully refreshed.", check index page [no change].

**Comment by putyourlightson** [comment]
I tested this again locally and it is working fine for me. Can you message me on slack or email info@putyourlightson.net so I can help you troubleshoot this further?

**Comment by wihodges** [comment]
Update 1.11.3 seems to have fixed it!

**Comment by putyourlightson** [comment]
Excellent, thanks for your help on solving this!
