### ISSUE TITLE
Refresh Expired removes entry from database but not file

### ISSUE THREAD

**Issue by Wiejeben** [putyourlightson/craft-blitz#624]
### Bug Report

Since the change in 4.11.0 we are experiencing issues with specifically our homepage from not regenerating after the page is expired.

Crontab:
```
*/5     *       *       *       *       cd /var/www && php craft blitz/cache/refresh-expired --queue
```

Our homepage setup:
```
{% do craft.blitz.options({
    trackElements: false,
    trackElementQueries: false,
    expiryDate: date('15 minutes'),
}) %}
```

When first loading the homepage it will appear as a row in the `blitz_caches` table with the uri as an empty value. After the expiry date was reached it will be removed from the database but when I got to my storage I can still see an `index.html` exists for the homepage. Since this `index.html` remains and I use an NGINX rewrite the page is never recreated.

Our refresh mode is "Clear the cache, regenerate manually or organically" with Blitz File Storage without gzip compression for our cache storage.

### Plugin Version

4.11.2

### Craft CMS Version

4.7.4

### PHP Version

8.2.8

**Comment by bencroker** [comment]
Thanks for reporting this, should have a fix out later today.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/aede7ea399ba69b19a08a084227c47eca0777f1d for the next release.

You can test this by running `composer require "putyourlightson/craft-blitz:dev-develop as 4.11.3"`.

**Comment by Wiejeben** [comment]
Installed the prerelease on Saturday, just checked it and issue still seems to exist unfortunately.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/244fae9fd940ebe16901b3f51bfbffc5326db47b as well!

**Comment by bencroker** [comment]
Released in [4.12.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.12.0).
