### ISSUE TITLE
Biltz only caching site homepage 

### ISSUE THREAD

**Issue by SETU-WEB** [putyourlightson/craft-blitz#733]
### Support Request

Hi 
We have been using Blitz cache for more than a year with no issues but today after the cache was cleared it now only caching the site homepage. We have a big site and use the clear the cache, regenerate manually or organically setting. But it's not generating cache now either manually or by running the generate cache command.

It runs through the process, but nothing is generated and there is only the homepage file in the cache directory. We haven't changed anything in the cache setting recently and the only system change we have made is charge the control panel path from admin to a new name.

I have cleared the cache, flushed the cache, and refreshed the cache but I still can't cache more than one page  

Craft edition & version: Pro 4.12.9
Blitz: 4.23.5

Thanks for any help 

### Plugin Version

 4.23.5

**Comment by bencroker** [comment]
Have you read the [common issues](https://putyourlightson.com/plugins/blitz#common-issues), specifically the first one? Enabling the `debug` config setting should log the reason for pages not being cached and help you track down the cause.

**Comment by SETU-WEB** [comment]
Hi Ben 
Yes  checked through those, none of the settings have changed, cache is enabled, and URI pattern is correct and unchanged. I have turned on debugging in the config but all I am getting is standard messages no errors logged. 
   '*' => [
        'debug' => true,

[2024-11-12 17:12:39] Blitz cache successfully cleared. [via console command by "]
[2024-11-12 17:14:10] Blitz cache successfully flushed. [via console command by ""]
[2024-11-12 17:17:08] Blitz cache successfully cleared. [via console command by ""]
[2024-11-12 17:17:08] Blitz cache successfully flushed. [via console command by ""]
[2024-11-12 17:17:23] Blitz cache generation complete. [via console command by ""]

![pic2](https://github.com/user-attachments/assets/998533e6-1453-4a5b-99c8-40d4d3f14655)

I'm the only one with admin access to the blitz settings and I haven't changed anything there in the last 6 months and it's worked brilliantly up to now

**Comment by bencroker** [comment]
With `debug` set to `true`, you should be seeing reasons for why pages are not being cached when either generating or when visiting them manually. Are you not seeing anything in the logs besides what you showed above?

**Comment by marina-moca** [comment]
Hi, we are also seeing this issue (after running maintenance updates to latest versions). 

![Google Chrome 2024-11-13 08 45 03](https://github.com/user-attachments/assets/c672e26b-bfd9-48b3-a5b9-e8abc7a8c00a)

![CleanShot 2024-11-13 at 09 49 32](https://github.com/user-attachments/assets/8b9831c3-edfa-4868-9f65-5f101a54fed1)

**Comment by marina-moca** [comment]
We have reverted to 4.23.3 and all ok.

**Comment by bencroker** [comment]
Thanks, @marina-moca. I'll look into what changed and see if I can spot the issue and release a fix soon.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/702658ee662bd6f116643d46333efca00057659a and released in [4.23.6](https://github.com/putyourlightson/craft-blitz/releases/tag/4.23.6) and [5.9.4](https://github.com/putyourlightson/craft-blitz/releases/tag/5.9.4). Please let me know if this resolves the issue for you.

**Comment by SETU-WEB** [comment]
Hi Ben 
I have updated but the issue isn't resolved. I ran the update via composer, flushed and cleared the cache and ran generate and I am still only getting a home page cached. The only difference this time is i am getting two query strings in my cache listing see screenshot 
![cache](https://github.com/user-attachments/assets/a81e7b05-2fd8-4b03-b308-7737198560c9)

**Comment by bencroker** [comment]
@SETU-WEB can you please send a Blitz diagnostics report so I can test using your setup locally?

**Comment by SETU-WEB** [comment]
Sure Ben here it is 
[diagnostics-report.md](https://github.com/user-attachments/files/17732853/diagnostics-report.md)

**Comment by bencroker** [comment]
Thanks. Can you please check the Blitz log file to see if there’s a reason that pages are not being cached?

From the report, I see that “Image transforms are configured not to be generated before page load”, which could be the issue.

**Comment by SETU-WEB** [comment]
Ok log is full of these messages 
[2024-11-13 13:55:16] Page not cached because a query string was provided with the query string caching setting disabled. [https://www.setu.ie/current-students/academic-calendar?p=current-students/academic-calendar]  but I don't want to cache query strings anyway. The" Image transforms are configured not to be generated before page load" has never been an issue up to now but should I add ->generateTransformsBeforePageLoad(true) to general.config

**Comment by SETU-WEB** [comment]
Ok log is full of these messages 
**[2024-11-13 13:55:16] Page not cached because a query string was provided with the query string caching setting disabled. [https://www.setu.ie/current-students/academic-calendar?p=current-students/academic-calendar]**  

but I don't want to cache query strings anyway . The" Image transforms are configured not to be generated before page load" has never been an issue up to now but should i add ->generateTransformsBeforePageLoad(true) to general.config

**Comment by SETU-WEB** [comment]
Ok I updated my config and have a green tick for images transforms now 

![picc](https://github.com/user-attachments/assets/40bda894-86c6-41cd-8b2d-e15db051d84a)

Still the same only caching the one page

**Comment by bencroker** [comment]
Would you be able to test the fix at https://github.com/putyourlightson/craft-blitz/commit/df7ff769b8f733098a01862c60e617db451cc235, since I cannot replicate this locally? You can do so by running `composer require "putyourlightson/craft-blitz:4.x-dev as 4.23.7"`.

**Comment by SETU-WEB** [comment]
Hey Ben, sorry I had to roll back to 4.23.3 (which is working fine) as we have a busy day today with lots of exam related traffic. I will upgrade to 4.23.7 tomorrow and tell you how it goes

**Comment by bencroker** [comment]
Sure thing!

**Comment by bencroker** [comment]
Released in [4.23.7](https://github.com/putyourlightson/craft-blitz/releases/tag/4.23.7) and [5.9.6](https://github.com/putyourlightson/craft-blitz/releases/tag/5.9.6).

**Comment by SETU-WEB** [comment]
Thanks ben, that latest update sorted the issue for me . Great support to get it fixed so quickly

**Comment by bencroker** [comment]
Glad to hear it, and thanks for sticking with me on this one!
