### ISSUE TITLE
Cache not getting cleared with other plugins

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#8]
Not sure where to post this but when I add a new calendar event with Calendar plugin and output them on my homepage, the cache does not get reset.

https://github.com/solspace/craft3-calendar

```
{% set events = craft.calendar.events({
order: 'startDate',
loadOccurrences: false,
rangeStart: now,
rangeEnd: '+ 6 month'
}).all() %}
```

**Comment by putyourlightson** [comment]
It is working in my tests. Are you on the latest versions of Blitz (1.3.0) and Calendar (2.0.4)?

**Comment by putyourlightson** [comment]
Ok, after some more testing I see how creating a new event can, in some circumstances, result in the cache not being cleared. This is a current limitation of the plugin not being able to detect new elements that will be output by a cached `craft.calendar.events` tag. I'll have to look into how to address this issue, for now it'll require a manual clearing of the cache in the utility.

**Comment by thaoms** [comment]
Thank you for looking into this!

**Comment by putyourlightson** [comment]
Development is under way :)

**Comment by putyourlightson** [comment]
Added automatic cache clearing and warming to pages that contain element queries in  https://github.com/putyourlightson/craft-blitz/commit/15eb83e48e55421d8a798a8d53bce7b213ffa0d3

**Comment by MarcHartwig13** [comment]
@putyourlightson I believe I'm running into a similar issue. I believe this functionality still works perfectly fine but the change in how `warm` works in 2.0 breaks it, at least for my use case. I'm also using the Calendar plugin and when I save a calendar event I can see the warm task run but because warm doesn't `flush` or `clear` cache my pages aren't being updated. I end up having to go to the entry that is connected to the calendar event and resave that to get the update event times.

Craft CMS: 3.3.1.2
Blitz: 2.1.5
Calendar: 2.0.24

From 1.x to 2.x `warm` doesn't flush or clear the cache. Does this part of Blitz need to be update to run `flush` and/or `cache` before `warm`? 

Appreciate the help and time!

**Comment by putyourlightson** [comment]
In Blitz 2, a `Refresh` is run before a `Warm` which does in fact clear the cache. Can you please create a new issue (since this one is resolved and closed) with details of your setup and I'll look into it further?

**Comment by MarcHartwig13** [comment]
Will do, sorry about commenting on a closed one. I'll gather some more details from the client and then post a new issue if their problem persists. I jumped the gun a little bit.

Thanks,
Marc
